name: Build

on:
  # schedule:
  #   - cron: "0 11 * * 1,3,5"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.1
      - name: Install Dependencies
        run: pnpm i
      - name: Fetch Data
        run: pnpm run fetch
      - name: Process Data
        run: pnpm process
      - name: Build Pages
        run: pnpm build
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: out
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
