name: Production Build

on:
  schedule:
    - cron: "0 17 3 * *" # MM03 1700 UTC (MM04 0000 GMT+7)
  workflow_dispatch:

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.1
      - name: Install Dependencies
        run: pnpm i
      - name: Fetch Data
        run: pnpm run fetch
      - name: Process Data
        run: pnpm process
      - name: Build Pages
        run: pnpm build
      - name: Upload data
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -avzr --omit-dir-times --no-owner --no-group --no-perms --delete
          path: out/
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
